### ISSUE TITLE
Don't turn of display while playing a video

### ISSUE THREAD

**Issue by Adurol** [llelectronics/videoPlayer#18]
**Feature Request: Add an option to disable turning off the display while playing a video**

When I play a video with the LLs vPlayer, the display will automatically reduce the brightness and then turn off after a given time as set in the Display Settings. It is really cumbersome to wake up the display via tap every time when watching a video. It would be nice to have an option in the settings of the player to turn of the powersaving of the display while playing a video (an re-enable it afterwards).

---
my Display Settings:
* Brightness: about 50%
* Adjust automatically: enabled
* Turn off after: 30 sec
---
LLs Video Player: v1.9
SailfishOS: 2.1.1.26
Hardware: Jolla TheFirstOne

**Comment by llelectronics** [comment]
This code here disables Screen suspension already: https://github.com/llelectronics/videoPlayer/blob/master/qml/pages/videoPlayer.qml#L793

Maybe you have a general issue with the dbus service. Have you tried restarting your phone. 
I am unable to reproduce the issue here neither on the Jolla 1, Jolla C or Jolla Tablet.

**Comment by Adurol** [comment]
Restarting the phone did the trick. Thank you.
I'm not sure what it is, but I assume an other app interfered and so it wasn't working (or maybe just some bit flipped 😒).

**Comment by llelectronics** [comment]
Good to know that it works now :)
