### ISSUE TITLE
Feature : Automatically switch to the next song (when in "browse files" mode)

### ISSUE THREAD

**Issue by sebma** [llelectronics/videoPlayer#7]
Hi,

Can you add the ability to automatically switch to the next song (when in "browse files" mode) ?

**Comment by llelectronics** [comment]
You can use playlists for this if you need a playlist. 
Otherwise I need to load the whole directory structure into memory to figure out what song comes next. 

Sorry this is something I don't want to do.

**Comment by sebma** [comment]
Hi,

Creating playlists for each directory I have can be a pain, espescially if I have to maintain them whenever I add new songs to different directories.

Why not load only the current directory level instead of doing it recursively ?

**Comment by llelectronics** [comment]
Current directory level loading in playlist is what I mean. It eats a lot of RAM depending on how much files there are that usually isn't wanted when only wanting to play one single file. 
I think I will add an option in the playlist editor itself to add whole folders (without subfolders) or find another more elegant way to do this.

**Comment by sebma** [comment]
I never wanted to play a single but the files in the current directory level, just like Unplayer does.

But Unplayer does not support the Opus codec, which gives a suprising audio quality at 32kbps :)

**Comment by llelectronics** [comment]
The problem is that LLs video player was never intended for that purpose and with 3 different plugins for file managing it isn't possible to accomplish this exactly the way you want it. However I added an option in two filemanagers to actually add all files from this directory to the playlist and show the playlist. 
Despite not being exactly what you wished for I think regarding your workflow this should pretty fine.
